name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version: ['27.1', '29.4', 'release-snapshot']
    steps:
      - uses: actions/checkout@v5
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Byte-compile
        run: make compile
      - name: Test
        run: make test
